services:
  tailscale:
    container_name: tailscale
    hostname: tailscaledocker           #根据实际主机名称修改
    image: tailscale/tailscale:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./data:/var/lib/tailscale
    environment:
      - TS_AUTH_KEY=XXXXXXXXXXXXXXXXXXXXXXXX           #tailscale申请key
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-routes=192.168.0.0/16